src/Entity/Collection.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection as DoctrineCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(
 *     name="collection",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="collection_identifier", columns={"collection_identifier"}),
 *         @ORM\UniqueConstraint(name="packrat_idx", columns={"packrat_id"})
 *     }
 * )
 * @ORM\Entity
 */
class Collection
{
    use Common\CostTrait;

    /**
     * @var int|null
     *
     * @ORM\Column(name="collection_id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var Family|null
     *
     * @ORM\ManyToOne(targetEntity="Family", inversedBy="collections")
     * @ORM\JoinColumn(referencedColumnName="family_id")
     */
    private $family;

    /**
     * @var Feat|null
     *
     * @ORM\OneToOne(targetEntity="Feat", mappedBy="collection")
     */
    private $feat;

    /**
     * @var DoctrineCollection
     *
     * @ORM\ManyToMany(targetEntity="Artist", inversedBy="collections")
     * @ORM\JoinTable(
     *     name="collection_artists",
     *     joinColumns={@ORM\JoinColumn(name="collection_id", referencedColumnName="collection_id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="artist_id", referencedColumnName="artist_id")}
     * )
     * @ORM\OrderBy({"name" = "ASC"})
     */
    private $artists;

    /**
     * @var DoctrineCollection
     *
     * @ORM\ManyToMany(targetEntity="Collection")
     * @ORM\JoinTable(
     *     name="related_collections",
     *     joinColumns={@ORM\JoinColumn(name="collection_id", referencedColumnName="collection_id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="related_collection_id", referencedColumnName="collection_id")}
     * )
     * @ORM\OrderBy({"name" = "ASC"})
     */
    private $relatedCollections;

    /**
     * @var DoctrineCollection
     *
     * @ORM\OneToMany(targetEntity="Card", mappedBy="collection")
     * @ORM\OrderBy({"displayOrder" = "ASC", "pointValue" = "DESC"})
     */
    private $cards;

    /**
     * @var int|null
     *
     * @ORM\Column(name="packrat_id", type="integer", nullable=false)
     */
    public $apiId;

    /**
     * @var string
     *
     * @ORM\Column(name="collection_identifier", type="string", length=100, nullable=false)
     */
    public $identifier;

    /**
     * @var string|null
     *
     * @ORM\Column(name="collection_name", type="string", length=100, nullable=true)
     */
    public $name;

    /**
     * @var string|null
     *
     * @ORM\Column(name="collection_icon", type="string", length=255, nullable=true)
     */
    public $icon;

    /**
     * @var int
     *
     * @ORM\Column(name="num_cards", type="smallint", nullable=false, options={"default" = 0})
     */
    public $numberOfCards = 0;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="release_date", type="date", nullable=true)
     */
    public $releaseDate;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="release_datetime", type="datetime", nullable=true)
     */
    public $apiReleaseDate;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="expiry_date", type="date", nullable=true)
     */
    public $expiryDate;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="expiry_datetime", type="datetime", nullable=true)
     */
    public $apiExpiryDate;

    /**
     * @var string|null
     *
     * @ORM\Column(name="intro_text", type="text", nullable=true)
     */
    public $introText;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_xl", type="boolean", nullable=false, options={"default" = false})
     */
    public $isXl = false;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_premium", type="boolean", nullable=false, options={"default" = false})
     */
    public $isPremium = false;

    /**
     * @var bool
     *
     * @ORM\Column(name="special_foils", type="boolean", nullable=false, options={"default" = false})
     */
    public $specialFoils = false;

    /**
     * @var string|null
     *
     * @ORM\Column(name="notes", type="text", nullable=true)
     */
    public $notes;

    /**
     * @var bool
     *
     * @ORM\Column(name="has_changed", type="boolean", nullable=false, options={"default" = false})
     */
    public $hasChanged = false;

    public function __construct()
    {
        $this->cards = new ArrayCollection();
        $this->artists = new ArrayCollection();
        $this->relatedCollections = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Family|null
     */
    public function getFamily(): ?Family
    {
        return $this->family;
    }

    /**
     * @param Family $family
     */
    public function setFamily(Family $family): void
    {
        $this->family = $family;
    }

    /**
     * @return Feat|null
     */
    public function getFeat(): ?Feat
    {
        return $this->feat;
    }

    /**
     * @param Feat $feat
     */
    public function setFeat(Feat $feat): void
    {
        $this->feat = $feat;
    }

    /**
     * @return DoctrineCollection
     */
    public function getCards(): DoctrineCollection
    {
        return $this->cards;
    }

    /**
     * @return int
     */
    public function getReleasedCards(): int
    {
        return $this->cards->count();
    }

    /**
     * @param Card $card
     */
    public function addCard(Card $card): void
    {
        if (!$this->cards->contains($card)) {
            $this->cards->add($card);
        }
    }

    /**
     * @return DoctrineCollection
     */
    public function getArtists(): DoctrineCollection
    {
        return $this->artists;
    }

    /**
     * @return bool
     */
    public function hasArtists(): bool
    {
        return $this->artists->count() > 0;
    }

    /**
     * @param Artist $artist
     */
    public function addArtist(Artist $artist): void
    {
        if (!$this->artists->contains($artist)) {
            $this->artists->add($artist);
        }
    }

    /**
     * @return DoctrineCollection
     */
    public function getRelatedCollections(): DoctrineCollection
    {
        return $this->relatedCollections;
    }

    /**
     * @return bool
     */
    public function hasRelatedCollections(): bool
    {
        return $this->relatedCollections->count() > 0;
    }

    /**
     * @param Collection $collection
     */
    public function addRelatedCollection(Collection $collection)
    {
        if (!$this->relatedCollections->contains($collection)) {
            $this->relatedCollections->add($collection);

            $collection->addRelatedCollection($this); // Reciprocal not not infinite
        }
    }

    /**
     * Retired or retiring in the next two weeka
     *
     * @return bool
     */
    public function isRetireding(): bool
    {
        if (null === $this->expiryDate) {
            return false;
        }

        $twoWeeks = strtotime('+2 week');

        return $twoWeeks >= $this->expiryDate->getTimestamp();
    }

    /**
     * @return bool
     */
    public function isRetired(): bool
    {
        if (null === $this->expiryDate) {
            return false;
        }

        return time() > $this->expiryDate->getTimestamp();
    }
}

src/Controller/InfoController.php
<?php

namespace App\Controller;

use App\Entity\Collection;
use App\Service\ArtistService;
use App\Service\CollectionService;
use App\Service\FamilyService;
use App\Service\FeatService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class InfoController extends AbstractController
{
    /**
     * @var CollectionService
     */
    private $collectionService;

    /**
     * @param CollectionService $collectionService
     */
    public function __construct(CollectionService $collectionService)
    {
        $this->collectionService = $collectionService;
    }

    /**
     * @param Request $request
     * @param ArtistService $artistService
     * @param FeatService $featService
     * @param FamilyService $familyService
     *
     * @Route("/api/info/", name="info")
     */
    public function index(
        Request $request,
        ArtistService $artistService,
        FeatService $featService,
        FamilyService $familyService
    ) {
        // @TODO: Handle redirects better
        if ($request->query->has('collection')) {
            return $this->redirectToRoute(
                'collection',
                ['identifier' => $request->query->get('collection')],
                Response::HTTP_PERMANENTLY_REDIRECT
            );
        }

        $gadgets = function (array $first) {
            return $first['family_id'] === 0; // Put gadgets last
        };

        $families = $familyService->getStatistics();
        $familyCards = $familyService->getCardStatistics();

        usort($families, $gadgets);
        usort($familyCards, $gadgets);

        return $this->render('info/index.html.twig', [
            'controller_name' => 'InfoController',
            'collections' => $this->collectionService->getCurrentCollections(),
            'artists' => $artistService->getStatistics(),
            'feats' => $featService->getStatistics(),
            'families' => $families,
            'familyCards' => $familyCards,
            'totalCollections' => array_sum(array_column($families, 'total')),
            'currentCollections' => array_sum(array_column($families, 'current')),
            'totalCards' => array_sum(array_column($familyCards, 'total')),
            'currentCards' => array_sum(array_column($familyCards, 'current')),
        ]);
    }

    /**
     * @Route("/api/info/collection/{identifier}", name="collection")
     */
    public function collection(Collection $collection)
    {
        return $this->render('info/collection.html.twig', [
            'controller_name' => 'InfoController',
            'collection' => $collection,
            'prevCollection' => $this->collectionService->getOneById($collection->getId() - 1),
            'nextCollection' => $this->collectionService->getOneById($collection->getId() + 1),
        ]);
    }
}

templates/info/_recipe.html.twig
{% if card.recipe.ingredient1 == card.recipe.ingredient2 and card.recipe.ingredient2 == card.recipe.ingredient3 %}
    3 x {# if alt collection then icon #} {{ card.recipe.ingredient1.name }} {# Card::drawCardTypeIcon($ing1['type'], $ing1['marketType']) #}
{% elseif card.recipe.ingredient1 == card.recipe.ingredient2 %}
    2 x {{ card.recipe.ingredient1.name }} + {{ card.recipe.ingredient3.name }} {# with icons and images as above #}
{% elseif card.recipe.ingredient2 == card.recipe.ingredient3 %}
    {{ card.recipe.ingredient1.name }} + 2 x {{ card.recipe.ingredient2.name }} {# with icons and images as above #}
{% else %}
    {{ card.recipe.ingredient1.name }} + {{ card.recipe.ingredient2.name }} + {{ card.recipe.ingredient3.name }} {# with icons and images as above #}
{% endif %}

{# highlight search term @TODO #}

templates/info/_sidebar.html.twig
<div class="filter">
    <form method="get" action="/info/" class="auto">
        <div>
            <select name="collection" onchange="this.form.submit();">
                <option value="">--View collection--</option>
                {#<?php foreach ($collections as $collection_id => $row) : ?>
                    <option value="<?php echo $row['collection_identifier']; ?>"<?php if (isset($_GET['collection']) && $row['collection_identifier'] == $_GET['collection']) :?> selected="selected"<?php endif; ?>><?php echo $row['collection_name']; ?></option>
                <?php endforeach; ?>#}
            </select>
            <span class="left">&nbsp;</span>
            <noscript>
                <p><input class="submit" type="submit" name="show" value="Show" /></p>
            </noscript>
        </div>
    </form>
    <br class="clear" />

    <div class="information">
        <h2><a href="/info/draw"><img src="{{ asset('images/packrat/draw.png') }}" alt="Bonus draw" title="Bonus draw" /> Bonus draws</a></h2>

        <p>View all the <a href="/info/draw">current bonus draw cards</a>.</p><br />

        <h2><a href="/info/new"><img src="{{ asset('images/packrat/trade.png') }}" alt="New releases" title="New releases" /> Newest releases</a></h2>

        {#<?php Card::drawNewCards($db_link, 10); ?>#}

        <p><a href="/info/new">View detailed releases from the last 5 days</a> &raquo;</p><br />

        <p><a href="http://twitter.com/packrattracker"><img src="{{ asset('images/twitter.png') }}" alt="Twitter" title="Follow us on Twitter" width="16" height="16" /> Follow us on Twitter</a> for latest card releases.</p>

    </div>
</div>

templates/info/index.html.twig
{% extends 'base.html.twig' %}

{% set route = 'info' %}

{% block title %}Packrat Recipes and Card Info{% endblock %}

{% block body %}
    <div class="content">
        <div>
            <h1 class="section_header left"><img src="{{ asset('images/packrat/vault.png') }}" alt="Collections" title="Collections" />&nbsp; Collections</h1>
            <p class="section_header left">
                <a href="{{ path('info') }}" class="selected">Current</a>
                | <a href="{{ path('info') }}?retired">Retired</a>
            </p>
        </div>

        <p class="section_header">
            <img src="{{ asset('images/packrat/steal.png') }}" alt="Order" title="Order" />&nbsp; Order:
            <a href="{{ path('info') }}" class="selected">Date</a>
            | <a href="{{ path('info') }}?order=name">Collection name</a>
        </p>
        <br class="clear" />

        {% for collection in collections %}
            <div class="minicard">
                <div>
                    <div class="collection-icon" style="border-bottom: 1px solid #{{ collection.family.border }}; background-color: #{{ collection.family.colour }};">
                        <p style="border: 1px solid #ffffff; background-color: #{{ collection.family.border }};">
                            <a href="/info/?collection={{ collection.identifier }}">
                                <img alt="{{ collection.name }}" width="16" height="16" src="{{ collection.icon }}" />
                            </a>
                        </p>
                    </div>
                    <p class="info">
                        {% if collection.isXl or collection.isPremium or collection.hasRelatedCollections %}
                            <span class="status">
                                {% if collection.isXl %}<img src="{{ asset('images/packrat/XL_16.png') }}" alt="XL" title="XL" class="is_xl" />{% endif %}
                                {% if collection.isPremium %}<img src="{{ asset('images/packrat/ticket-flat_16.png') }}" alt="Premium" title="Premium" class="is_premium" />{% endif %}
                            </span>

                            {% if collection.hasRelatedCollections %}
                                <span class="related">
                                    {% for altCollection in collection.relatedCollections %}
                                        <a href="/info/?collection={{ altCollection.identifier }}"><img width="16" height="16" src="{{ altCollection.icon }}" alt="{{ altCollection.name }}" title="{{ altCollection.name }}" /></a>
                                    {% endfor %}
                                </span>
                            {% endif %}
                        {% endif %}

                        <span class="name"><a href="/info/?collection={{ collection.identifier }}">{{ collection.name }}</a></span>
                        <span class="details">
                            {% if collection.numberOfCards != collection.releasedCards %}{{ collection.releasedCards }}/{% endif %}{{ collection.numberOfCards }}
                            Card{% if collection.numberOfCards != 1 %}s{% endif %}
                        </span>
                    </p>

                    <p class="bottom{% if collection.retireding %} expired{% endif %}">
                        {% if collection.retireding %}
                            <span class="bl expired">
                                {% if collection.retired %}Retired {% else %}Retiring {% endif %} on
                                {{ collection.expiryDate|date('d M Y') }}
                            </span>
                        {% else %}
                            <span class="bl">
                                Released on
                                {{ collection.releaseDate|date('d M Y') }}
                                {% if collection.expiryDate is not empty %}*{% endif %}
                            </span>
                        {% endif %}
                    </p>
                </div>
            </div>
        {% endfor %}

        <br class="clear" /><br />

        <div>* Retiring in over 2 weeks time</div>

        <br class="clear" /><br />

        {# if current show artists, feats, statistics #}
        <h1 id="artists"><img src="{{ asset('images/packrat/packrat.png') }}" alt="Artists" title="Artists" />&nbsp; Artists</h1>

        {% for artist in artists %}
            <div class="minicard">
                <div>
                    <div class="collection-icon" style="border-bottom: 1px solid #{{ artist.artist_colour }}; background-color: #cccccc;">
                        <p style="border: 1px solid #ffffff; background-color: #{{ artist.artist_colour }};">
                            <a href="/info/?artist={{ artist.artist_identifier }}"><img alt="{{ artist.artist_name|raw }}" width="16" height="16" src="{{ artist.artist_icon }}" /></a>
                        </p>
                    </div>
                    <p class="info two_line">
                        <span class="name"><a href="/info/?artist={{ artist.artist_identifier }}">{{ artist.artist_name|raw }}</a></span>
                        <span class="details">{{ artist.total }} collections ({{ artist.current }} current)</span>
                    </p>
                    <p class="bottom">&nbsp;</p>
                </div>
            </div>
        {% endfor %}

        <br class="clear" /><br />

        <h1 id="feats"><img src="{{ asset('images/packrat/vault.png') }}" alt="Feats" title="Feats" />&nbsp; Feats</h1>

        <div class="minicard">
            <div>
                <div class="collection-icon" style="border-bottom: 1px solid #4d4d4d; background-color: #cccccc;">
                    <p style="border: 1px solid #ffffff; background-color: #4d4d4d;">
                        <a href="/info/feats"><img alt="Collection Feats" src="{{ asset('images/packrat-icon.gif') }}" /></a>
                    </p>
                </div>
                <p class="info two_line">
                    <span class="name"><a href="/info/feats">Collection Feats</a></span>
                    <span class="details">{{ feats.collections }}/{{ feats.total }} feats ({{ feats.currentCollections }} current)</span>
                </p>
                <p class="bottom">&nbsp;</p>
            </div>
        </div>

        <div class="minicard">
            <div>
                <div class="collection-icon" style="border-bottom: 1px solid #4d4d4d; background-color: #cccccc;">
                    <p style="border: 1px solid #ffffff; background-color: #4d4d4d;">
                        <a href="/info/feats?task"><img alt="Achievement Feats" src="{{ asset('images/packrat-icon.gif') }}" /></a>
                    </p>
                </div>
                <p class="info two_line">
                    <span class="name"><a href="/info/feats?task">Achievements</a></span>
                    <span class="details">{{ feats.achievements }}/{{ feats.total }} feats ({{ feats.currentAchievements }} current)</span>
                </p>
                <p class="bottom">&nbsp;</p>
            </div>
        </div>

        <br class="clear" /><br />

        <h1><img src="{{ asset('images/packrat/vault.png') }}" alt="Statistics" title="Statistics" />&nbsp; Statistics</h1>

        <div class="minicard">
            <div>
                <div class="collection-icon" style="border-bottom: 1px solid #4d4d4d; background-color: #cccccc;">
                    <p style="border: 1px solid #ffffff; background-color: #4d4d4d;">
                        <a href="/info/"><img alt="All Collections" src="{{ asset('images/packrat-icon.gif') }}" /></a>
                    </p>
                </div>
                <p class="info two_line">
                    <span class="name"><a href="/info/">All</a></span>
                    <span class="details">{{ totalCollections }} Collections ({{ currentCollections }} current)<br />
                    {{ totalCards }} Cards ({{ currentCards }} current)</span>
                </p>
                <p class="bottom">&nbsp;</p>
            </div>
        </div>

        {% for index, family in families %}
            <div class="minicard">
                <div>
                    <div class="collection-icon" style="border-bottom: 1px solid #{{ family.family_border }}; background-color: #{{ family.family_colour }};">
                        <p style="border: 1px solid #ffffff; background-color: #{{ family.family_border }};">
                            <a href="/info/?family={{ family.family_identifier }}"><img alt="{{ family.family_name }}" src="{{ asset('images/foils/' ~ family.family_icon) }}" /></a>
                        </p>
                    </div>
                    <p class="info two_line">
                        <span class="name"><a href="/info/?family={{ family.family_identifier }}">{{ family.family_name }}</a></span>
                        <span class="details">
                            {{ family.total }} {% if 0 != family.family_id %}Collections ({{ family.current }} current){% else %}Sets{% endif %}<br />
                            {{ familyCards[index].total }} {% if 0 != family.family_id %}Cards ({{ familyCards[index].current }} current){% else %}Gadgets{% endif %}
                        </span>
                    </p>
                    <p class="bottom">&nbsp;</p>
                </div>
            </div>
        {% endfor %}

        <br class="clear" />
    </div>

    {% include 'info/_sidebar.html.twig' %}
{% endblock %}